when:
  - event: [push, manual]
    branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: build
    image: ghcr.io/astral-sh/uv:python3.12-bookworm-slim
    commands:
      - apt-get update && apt-get install -y git
      - uv sync
      - uv run mkdocs build -d site-build

  - name: deploy
    image: appleboy/drone-git-push
    settings:
      branch: pages
      remote: git@codeberg.org:${CI_REPO}.git
      force: true
      commit: true
      commit_message: "Deploy: ${CI_COMMIT_SHA:0:7}"
      path: site-build
      skip_host_key_check: true
      password:
        from_secret: EPHEM_PAGES
    when:
      - branch: ${CI_REPO_DEFAULT_BRANCH}
