when:
  - event: [push, manual]
    branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: build
    image: ghcr.io/astral-sh/uv:python3.12-bookworm-slim
    commands:
      - apt-get update && apt-get install -y git
      - uv sync
      - uv run mkdocs build -d site-build

  - name: deploy
    image: appleboy/drone-git-push
    settings:
      branch: pages
      remote: https://codeberg.org/sailorfe/ephem.git
      password:
        from_secret: EPHEM_PAGES
      force: true
      commit: true
      path: site-build
