when:
  - event: [push, manual]
    branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: build
    image: ghcr.io/astral-sh/uv:python3.12-bookworm-slim
    commands:
      - apt-get update && apt-get install -y git
      - uv sync
      - uv run mkdocs build -d site-build

  - name: deploy
    image: alpine/git
    environment:
      CB_TOKEN:
        from_secret: EPHEM_PAGES
    commands:
      - cd site-build
      - git init -b main
      - git config user.name "sailorfe"
      - git config user.email "sailorfe@noreply.codeberg.org"
      - git add .
      - git commit -m "Deploy docs [skip ci]"
      - git push --force https://sailorfe:$${CB_TOKEN}@codeberg.org/sailorfe/ephem.git main:pages
